### ISSUE TITLE
Support Pulsar SSL?

### ISSUE THREAD

**Issue by christbiz86** [streamnative/pulsar-beat-output#21]
Hi, is it support for pulsar SSL? Because i've create pulsar client with SSL. 

@tuteng can you help with this issue?

Thanks.

**Comment by christbiz86** [comment]
i found it anyway

hosts: ["pulsar+ssl://pulsar-authentication:6651"]
  use_tls: true
  tls_trust_certs_file_path: /go/src/github.com/streamnative/pulsar-beat-output/certs/ca.cert.pem
  certificate_path: /go/src/github.com/streamnative/pulsar-beat-output/role/admin.cert.pem
  private_key_path: /go/src/github.com/streamnative/pulsar-beat-output/role/admin.key-pk8.pem
  url: "pulsar+ssl://pulsar-authentication:6651"
  topic: my_topic2

**Comment by christbiz86** [comment]
@tuteng what the syntax for auth? on pulsar config example :
Authentication:             pulsar.NewAuthenticationToken("xxxxxx-xxxxx-xxxxx")

**Comment by tuteng** [comment]
> i found it anyway
> 
> hosts: ["pulsar+ssl://pulsar-authentication:6651"]
> use_tls: true
> tls_trust_certs_file_path: /go/src/github.com/streamnative/pulsar-beat-output/certs/ca.cert.pem
> certificate_path: /go/src/github.com/streamnative/pulsar-beat-output/role/admin.cert.pem
> private_key_path: /go/src/github.com/streamnative/pulsar-beat-output/role/admin.key-pk8.pem
> url: "pulsar+ssl://pulsar-authentication:6651"
> topic: my_topic2

I think this configuration is correct for supporting ssl

**Comment by christbiz86** [comment]
Yeah, but i have SSL parameters like below :

client, err := pulsar.NewClient(pulsar.ClientOptions{
      URL:                        "pulsar+ssl://pulsar-authentication:6651",
      TLSTrustCertsFilePath:      "./ca.cert.pem",
      Authentication:             pulsar.NewAuthenticationToken("xxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxx"),
      TLSAllowInsecureConnection: false,
   })

where i can put the "Authentication" params on the configuration supporting SSL?
