### ISSUE TITLE
[bug report]  BatchingMaxPublishDelay conf init error

### ISSUE THREAD

**Issue by holmes07** [streamnative/pulsar-beat-output#34]
### happens at
if config.BatchingMaxPublishDelay > 0 {
		producerOptions.BatchingMaxPublishDelay = config.BatchingMaxPublishDelay  * time.Second
}

### desc
The delay time will amplification 1000000000  ，Timer Will not execute as expected

### solution 
remove code  * time.Millisecond

if config.BatchingMaxPublishDelay > 0 {
		producerOptions.BatchingMaxPublishDelay = config.BatchingMaxPublishDelay
}

**Comment by hezhangjian** [comment]
close due to #35
