### ISSUE TITLE
不支持最新版pulsar

### ISSUE THREAD

**Issue by wthahaha** [streamnative/pulsar-beat-output#79]
只支持pulsar2.3.2，不支持最新版pulsar，最好不要用这个了

**Comment by hezhangjian** [comment]
Can you explain nore why it can't works along with latest pulsar verin?

**Comment by wthahaha** [comment]
look, dockerfile里只有pulsar2.3.0
![image](https://user-images.githubusercontent.com/19517430/188364521-d36ae765-3b00-4dbe-8968-57d2b61d42ff.png)

**Comment by hezhangjian** [comment]
I think the dockerfile is outdated. And I think it's used for build before. Could you please try the binary?

**Comment by wthahaha** [comment]
oh，谢谢，
请教一下大佬，如果我想使用最新的packetbeat和最新的pulsar，我该如何修改这个项目，使之符合我的需求呢？

**Comment by hezhangjian** [comment]
You can update the dependency in the go.mod, and build binary in the packetbeat folder

**Comment by wthahaha** [comment]
我测试了一下，最高只能支持到beat7.17.6,无法把8版本的beat编译进去，可能我弄得不对。大佬们是否能更新下代码，以支持最新版的beat和pulsar？谢谢。

**Comment by douglarek** [comment]
> 我测试了一下，最高只能支持到beat7.17.6,无法把8版本的beat编译进去，可能我弄得不对。大佬们是否能更新下代码，以支持最新版的beat和pulsar？谢谢。

Please refer to https://github.com/douglarek/beat-pulsar-output, but I have only tested it on the 7.x branch.
